version: '2'
services:
  app:
    build: .
    restart: always
    ports:
      - 61234:61234
    environment:
      TCPDUMP_ENABLE: 'true'
      CTF_PORT: 61234
    volumes:
      - ./tcpdump/:/var/lib/tcpdump
